services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"
    environment:
      - PORT=80
    depends_on:
      - backend

  redis:
    image: redis
    ports:
      - "6379:6379"
